import { GetStaticProps } from 'next'
import Head from 'next/head'
import CountriesGrid from '../components/CountriesGrid'
import FilterSearch from '../components/FilterSearch'
import Navbar from '../components/Navbar'
import SearchInput from '../components/SearchInput'
import {Country} from '../components/CountryComp';

interface HomeProps{
  countries: Country[];
}

export default function Home({countries}:HomeProps) {
	
  // Mapping through every country's region and using Set to avoid repetitions.
	const filteredRegions = Array.from(
		new Set(countries.map((country) => country.region))
	);

	// Removing invalid regions and sorting array alphabetically.
  const regions: string[] = filteredRegions
		.slice(0, filteredRegions.length - 2)
		.sort((a, b) => {
			if (a > b) return 1;
			if (a < b) return -1;
			return 0;
		});


	return (
		<div className='bg-veryLightGray min-h-screen'>
			<Head>
				<title>World Countries</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<header>
				<Navbar />
			</header>

			<main className='mx-6 lg:mx-8'>
				<div className='lg:flex lg:justify-between'>
					<SearchInput />
					<FilterSearch regions={regions} />
				</div>

				<CountriesGrid countries={countries} />
			</main>
		</div>
	);
}

export const getStaticProps: GetStaticProps = async () =>{

  const response = await fetch('https://restcountries.eu/rest/v2/all');
  const data = await response.json();

  const countries:Country[] = data.map((country) => {

    const {alpha3Code, capital, currencies, borders, flag, languages,name, nativeName, population, region, subregion, topLevelDomain} = country;

    return{
      id: alpha3Code,
      name,
      nativeName,
      population, 
      region,
      subRegion: subregion, 
      capital,
      topLevelDomain,
      currencies, 
      languages,
      borderCountries: borders,
      flag
    }
  });

  return {
    props: {
      countries
    }
  }
}
