import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>The CocktailDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-red-400'>Hello, Next + Tailwind + Typescript</h1>
    </div>
  )
}
